CREATE TYPE cuenta_bancaria AS OBJECT (
num_cuenta  VARCHAR2(30),
saldo NUMBER,
estado VARCHAR2(7),
CONSTRUCTOR FUNCTION Cuenta_Bancaria RETURN SELF AS RESULT
MEMBER PROCEDURE verificar,
MEMBER PROCEDURE cerrar (cantidad OUT REAL),
MEMBER PROCEDURE ingresar (cantidad IN REAL),
MEMBER PROCEDURE retirar (cantidad IN REAL),
MEMBER FUNCTION saldo_actual RETURN REAL
);

CREATE SEQUENCE numeroCuenta
INCREMENT BY 100
STARTS WITH 100;


CREATE OR REPLACE TYPE BODY job2 AS
CONSTRUCTOR FUNCTION rectangle(length NUMBER, width NUMBER)
RETURN SELF AS RESULT
AS
BEGIN

END; 

MEMBER PROCEDURE verificar  IS
BEGIN

END; 

MEMBER PROCEDURE cerrar (cantidad OUT REAL) IS
BEGIN

END; 

MEMBER PROCEDURE ingresar (cantidad IN REAL) IS
BEGIN

END; 

MEMBER PROCEDURE retirar (cantidad IN REAL) IS
BEGIN

END; 

MEMBER FUNCTION saldo_actual RETURN REAL IS
BEGIN

END; 



END;