--1
USE NOTAS;
CREATE TABLE IF NOT EXISTS NOTAS(
APELLIDOS VARCHAR(30),
NOMBRE VARCHAR(30),
NIF VARCHAR(30),
INV_COMERCIAL INT(2),
MARKETING INT(2),
Log_Comerc INT(2),
Mark_PV INT(2),
COMP INT(2),
APLIC_INF INT(2),
LENG_EXTR INT(2),
IDIOMAS INT(2),
CONSTRAINT PK_NIF PRIMARY KEY(NIF)
);

LOAD DATA INFILE 'E:\\Base de datos\\Bases de datos\\notas.csv'
INTO TABLE NOTAS
FIELDS TERMINATED BY ';' ENCLOSED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

--a
SELECT NOMBRE, APELLIDOS FROM NOTAS
ORDER BY INV_COMERCIAL + MARKETING + Log_Comerc + Mark_PV 
+ COMP + APLIC_INF + LENG_EXTR + IDIOMAS DESC LIMIT 1;

--b
SELECT NOMBRE, APELLIDOS FROM NOTAS
ORDER BY INV_COMERCIAL + MARKETING + Log_Comerc + Mark_PV 
+ COMP + APLIC_INF + LENG_EXTR + IDIOMAS ASC LIMIT 1;

--c
SELECT AVG(INV_COMERCIAL),AVG(MARKETING),AVG(Log_Comerc),
AVG(Mark_PV),AVG(COMP),AVG(APLIC_INF),
AVG(LENG_EXTR),AVG(IDIOMAS) FROM NOTAS;

--2
USE codigo_postal;
CREATE TABLE IF NOT EXISTS CP(
ID INT(7) AUTO_INCREMENT,
PROVINCIA VARCHAR(15),
POBLACION VARCHAR(30),
CODIGOPOSTAL INT(5),
CONSTRAINT PK_ID PRIMARY KEY(ID)
);

LOAD DATA INFILE 'E:\\Base de datos\\Bases de datos\\codpost.txt'
INTO TABLE CP
FIELDS TERMINATED BY ';' ENCLOSED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 7 LINES
(PROVINCIA, POBLACION, CODIGOPOSTAL);


