--1

CREATE TABLE empleados_sin_comision 
SELECT EMP_NO, APELLIDO, DNOMBRE FROM EMPLEADOS E 
JOIN DEPARTAMENTOS D ON E.DEP_NO=D.DEP_NO
WHERE COMISION IS NULL;

--2

CREATE VIEW empleados_directores AS
SELECT EMP_NO AS empleado_no, 
APELLIDO AS apellido, 
SUM(SALARIO*14) AS salario_anual
FROM EMPLEADOS
WHERE OFICIO = 'DIRECTOR'
group by EMP_NO;

SELECT empleado_no, apellido
FROM empleados_directores
WHERE salario_anual > 50000;

--3

CREATE VIEW jefes AS
SELECT A.APELLIDO, IFNULL(COUNT(B.DIRECTOR),0) FROM EMPLEADOS A LEFT JOIN EMPLEADOS B ON B.DIRECTOR = A.EMP_NO GROUP BY A.EMP_NO;

--4.a

UPDATE CLIENTES C
SET LIMITE_CREDITO = LIMITE_CREDITO * 1.2
WHERE 3<(SELECT COUNT(PEDIDO_NO) FROM PEDIDOS P GROUP BY P.CLIENTE_NO HAVING P.CLIENTE_NO = C.CLIENTE_NO);

--4.b

CREATE VIEW CLIENTES_TRES AS
SELECT CLIENTE_NO, COUNT(PEDIDO_NO)
FROM PEDIDOS
GROUP BY CLIENTE_NO
HAVING COUNT(PEDIDO_NO)>3;

UPDATE CLIENTES C, CLIENTES_TRES C3
SET C.LIMITE_CREDITO = C.LIMITE_CREDITO*1.2
WHERE C.CLIENTE_NO = C3.CLIENTE_NO;


