CREATE TABLE  COMPRADORES(
CIF_comprador CHAR(11),
Nombre_social VARCHAR(30),
Domicilio_social VARCHAR(30),
Localidad VARCHAR(30),
C_postal CHAR(5),
Teléfono CHAR(9) NOT NULL,
CONSTRAINT PK_COMPRADORES_CIF PRIMARY KEY(CIF_comprador),
CONSTRAINT UQ_COMPRADORES_NOMBRE_SOCIAL UNIQUE(Nombre_social));

CREATE TABLE ARTICULOS(
Referencia_articulo CHAR(12),
Descripcion_articulo VARCHAR(30),
Precio_unidad FLOAT(6,2),
IVA INT(2),
Existencias_actuales INT(5) DEFAULT 0,
CONSTRAINT PK_ARTICULOS PRIMARY KEY(Referencia_articulo));

CREATE TABLE FACTURAS(
Factura_no INT(6) AUTO_INCREMENT,
Fecha_factura DATE DEFAULT "2005-01-01",
CIF_Cliente CHAR(11),
CONSTRAINT PK_FACTURAS PRIMARY KEY(Factura_no));

CREATE TABLE LINEAS_FACTURAS(
Factura_no INT(6),
Referencia_articulo CHAR(11),
Unidades INT(3),
CONSTRAINT PK_LINEAS_FACTURA PRIMARY KEY(Factura_no, Referencia_articulo),
CONSTRAINT FK_LINEAS_FACTURAS FOREIGN KEY(Factura_no) REFERENCES FACTURAS(Factura_no) ON DELETE CASCADE,
CONSTRAINT FK_LINEAS_ARTICULOS FOREIGN KEY(Referencia_articulo) REFERENCES ARTICULOS(Referencia_articulo) ON UPDATE CASCADE);

ALTER TABLE FACTURAS ADD (cod_oficina INT(4));
ALTER TABLE FACTURAS ADD (cif_cliente CHAR(11));
ALTER TABLE FACTURAS ADD (CONSTRAINT FK_CIF_CLIENTE FOREIGN KEY(cif_cliente) REFERENCES COMPRADORES(CIF_comprador));
ALTER TABLE COMPRADORES CHANGE C_postal codigo_postal CHAR(5);
